orgs/enterprise/blackbox-huginn/config/routes.rb
Rails.application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      post :reemit_events
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

orgs/enterprise/blackbox-huginn/app/views/layouts/_messages.html.erb
<% if flash.keys.length > 0 %>
  <div class="flash">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name.to_sym == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
<% end %>

orgs/enterprise/blackbox-huginn/app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "Huginn", root_path, :class => 'navbar-brand' %>
</div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  
  <% if user_signed_in? %>
    <ul class='nav navbar-nav'>
      <%= nav_link "Agents", agents_path do %>
        <ul class='dropdown-menu' role='menu'>
          <%= nav_link icon_tag('glyphicon-plus') + " New Agent", new_agent_path %>
          <%= nav_link icon_tag('glyphicon-refresh') + " Run event propagation", propagate_agents_path, method: 'post' %>
          <%= nav_link icon_tag('glyphicon-random') + " View Diagram", diagram_path %>
        </ul>
      <% end %>
      <%= nav_link "Scenarios", scenarios_path %>
      <%= nav_link "Events", events_path %>
      <%= nav_link "Credentials", user_credentials_path %>
      <%= nav_link "Services", services_path %>
    </ul>
  <% end %>
  
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" id='agent-navigate' autocomplete="off" placeholder="Search">
          <%= image_tag "spinner-arrows.gif", :class => "spinner" %>
        </div>
      </form>
      
      <li class='job-indicator' role='pending'>
        <%= link_to current_user.admin? ? jobs_path : '#' do %>
          <span class="badge"><%= icon_tag('glyphicon-refresh', class: 'icon-white') %> <span class='number'>0</span></span>
        <% end %>
      </li>
      <li class='job-indicator' role='awaiting_retry'>
        <%= link_to current_user.admin? ? jobs_path : '#' do %>
          <span class="badge"><%= icon_tag('glyphicon-question-sign', class: 'icon-yellow') %> <span class='number'>0</span></span>
        <% end %>
      </li>
      <li class='job-indicator' role='recent_failures'>
        <%= link_to current_user.admin? ? jobs_path : '#', class: 'hidden-sm hidden-xs' do %>
        <span class="badge"><%= icon_tag('glyphicon-exclamation-sign', class: 'icon-white') %> <span class='number'>0</span></span>
        <% end %>
      </li>
      <li id='event-indicator'>
        <a href="#" class='hidden-sm hidden-xs'>
          <span class="badge"><%= icon_tag('glyphicon-random', class: 'icon-white') %> <span class='number'>0</span> events</span>
        </a>
      </li>
    <% end %>
    
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account
        <% if user_signed_in? && session[:original_admin_user_id].present? %>
          <span class="label label-warning"><%= current_user.username %></span>
        <% end %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <% if user_signed_in? && session[:original_admin_user_id].present? %>
          <li>
            <%= link_to 'Switch Back to Admin User', switch_back_admin_users_path, tabindex: '-1' %>
          </li>
        <% end %>
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Account', edit_user_registration_path, :tabindex => "-1" %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, :tabindex => "-1" %>
          <% end %>
        </li>
        <% if user_signed_in? && current_user.admin %>
          <li>
            <%= link_to 'Job Management', jobs_path, :tabindex => '-1' %>
          </li>
          <li>
            <%= link_to 'User Management', admin_users_path, tabindex: '-1' %>
          </li>
        <% end %>
        <li>
          <%= link_to 'About', 'https://github.com/huginn/huginn', :tabindex => "-1" %>
        </li>

        <li>
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :tabindex => "-1" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, :tabindex => "-1" %>
          <% end %>
        </li>
      </ul>
    </li>

  </ul>
</div>

orgs/enterprise/blackbox-huginn/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " - Huginn" : "Huginn" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico" sizes="16x16">
    <link rel="icon" type="image/png" href="/android-chrome-48x48.png" sizes="48x48">
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
    <link rel="manifest" href="/manifest.json">
    <%= yield(:ace_editor_script) %>
    <%= yield(:head) %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>

    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      <% if user_signed_in? %>
        <%= render "upgrade_warning" %>
      <% end %>

      <div id="main-content">
        <%= yield %>
      </div>
      
    </div>

    <script>
      window.agentPaths = {};
      window.agentNames = [];
      <% if current_user.present? -%>
        var myAgents = <%= Utils.jsonify(current_user.agents.pluck(:name, :id).inject({}) {|m, a| next if a.last.nil?; m[a.first] = agent_path(a.last); m }) %>;
        var myScenarios = <%= Utils.jsonify(current_user.scenarios.pluck(:name, :id).inject({}) {|m, s| m[s.first + " Scenario"] = scenario_path(s.last); m }) %>;
        $.extend(window.agentPaths, myAgents);
        $.extend(window.agentPaths, myScenarios);
        window.agentPaths["All Agents Index"] = <%= Utils.jsonify agents_path %>;
        window.agentPaths["New Agent"] = <%= Utils.jsonify new_agent_path %>;
        window.agentPaths["Account"] = <%= Utils.jsonify edit_user_registration_path %>;
        window.agentPaths["Events Index"] = <%= Utils.jsonify events_path %>;
        window.agentPaths["View Agent Diagram"] = <%= Utils.jsonify diagram_path %>;
        window.agentPaths["Run Event Propagation"] = { url: <%= Utils.jsonify propagate_agents_path %>, method: 'POST' };

        $.each(window.agentPaths, function(name, v) { window.agentNames.push(name); });
      <% end -%>
    </script>
  </body>
</html>