orgs/enterprise/blackbox-huginn/config/routes.rb
Rails.application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      post :reemit_events
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

orgs/enterprise/blackbox-huginn/app/models/agent.rb
require 'utils'

# Agent is the core class in Huginn, representing a configurable, schedulable, reactive system with memory that can
# be sub-classed for many different purposes.  Agents can emit Events, as well as receive them and react in many different ways.
# The basic Agent API is detailed on the Huginn wiki: https://github.com/huginn/huginn/wiki/Creating-a-new-agent
class Agent < ActiveRecord::Base
  include AssignableTypes
  include MarkdownClassAttributes
  include JsonSerializedField
  include RdbmsFunctions
  include WorkingHelpers
  include LiquidInterpolatable
  include HasGuid
  include DryRunnable
  include SortableEvents

  markdown_class_attributes :description, :event_description

  load_types_in "Agents"

  SCHEDULES = %w[
    every_1m every_2m every_5m every_10m every_30m
    every_1h every_2h every_5h every_12h
    every_1d every_2d every_7d
    midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am
    noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm
    never
  ]

  EVENT_RETENTION_SCHEDULES = [
    ["Forever", 0], ['1 hour', 1.hour], ['6 hours', 6.hours], ["1 day", 1.day],
    *(
      [2, 3, 4, 5, 7, 14, 21, 30, 45, 90, 180, 365].map { |n|
        ["#{n} days", n.days]
      }
    )
  ]

  json_serialize :options, :memory

  validates_presence_of :name, :user
  validates_inclusion_of :keep_events_for, in: EVENT_RETENTION_SCHEDULES.map(&:last)
  validates :sources, owned_by: :user_id
  validates :receivers, owned_by: :user_id
  validates :controllers, owned_by: :user_id
  validates :control_targets, owned_by: :user_id
  validates :scenarios, owned_by: :user_id
  validate :validate_schedule
  validate :validate_options

  after_initialize :set_default_schedule
  before_validation :set_default_schedule
  before_validation :unschedule_if_cannot_schedule
  before_save :unschedule_if_cannot_schedule
  before_create :set_last_checked_event_id
  after_save :possibly_update_event_expirations

  belongs_to :user, inverse_of: :agents
  belongs_to :service, inverse_of: :agents, optional: true
  has_many :events, -> { order("events.id desc") }, dependent: :delete_all, inverse_of: :agent
  has_one  :most_recent_event, -> { order("events.id desc") }, inverse_of: :agent, class_name: "Event"
  has_many :logs, -> { order("agent_logs.id desc") }, dependent: :delete_all, inverse_of: :agent, class_name: "AgentLog"
  has_many :links_as_source, dependent: :delete_all, foreign_key: "source_id", class_name: "Link",
                             inverse_of: :source
  has_many :links_as_receiver, dependent: :delete_all, foreign_key: "receiver_id", class_name: "Link",
                               inverse_of: :receiver
  has_many :sources, through: :links_as_receiver, class_name: "Agent", inverse_of: :receivers
  has_many :received_events, -> { order("events.id desc") }, through: :sources, class_name: "Event", source: :events
  has_many :receivers, through: :links_as_source, class_name: "Agent", inverse_of: :sources
  has_many :control_links_as_controller, dependent: :delete_all, foreign_key: 'controller_id',
                                         class_name: 'ControlLink', inverse_of: :controller
  has_many :control_links_as_control_target, dependent: :delete_all, foreign_key: 'control_target_id',
                                             class_name: 'ControlLink', inverse_of: :control_target
  has_many :controllers, through: :control_links_as_control_target, class_name: "Agent", inverse_of: :control_targets
  has_many :control_targets, through: :control_links_as_controller, class_name: "Agent", inverse_of: :controllers
  has_many :scenario_memberships, dependent: :destroy, inverse_of: :agent
  has_many :scenarios, through: :scenario_memberships, inverse_of: :agents

  scope :active,   -> { where(disabled: false, deactivated: false) }
  scope :inactive, -> { where(disabled: true).or(where(deactivated: true)) }

  scope :of_type, ->(type) {
    case type
    when Agent
      where(type: type.class.to_s)
    else
      where(type: type.to_s)
    end
  }

  def short_type
    type.demodulize
  end

  def check
    # Implement me in your subclass of Agent.
  end

  def default_options
    # Implement me in your subclass of Agent.
    {}
  end

  def receive(events)
    # Implement me in your subclass of Agent.
  end

  def is_form_configurable?
    false
  end

  def receive_web_request(params, method, format)
    # Implement me in your subclass of Agent.
    ["not implemented", 404, "text/plain", {}] # last two elements in response array are optional
  end

  # alternate method signature for receive_web_request
  # def receive_web_request(request=ActionDispatch::Request.new( ... ))
  # end

  # Implement me in your subclass to decide if your Agent is working.
  def working?
    raise "Implement me in your subclass"
  end

  def build_event(event)
    event = events.build(event) if event.is_a?(Hash)
    event.agent = self
    event.user = user
    event.expires_at ||= new_event_expiration_date
    event
  end

  def create_event(event)
    if can_create_events?
      event = build_event(event)
      event.save!
      event
    else
      error "This Agent cannot create events!"
    end
  end

  def credential(name)
    @credential_cache ||= {}
    if @credential_cache.has_key?(name)
      @credential_cache[name]
    else
      @credential_cache[name] = user.user_credentials.where(credential_name: name).first.try(:credential_value)
    end
  end

  def reload(...)
    @credential_cache = {}
    super
  end

  def new_event_expiration_date
    keep_events_for > 0 ? keep_events_for.seconds.from_now : nil
  end

  def update_event_expirations!
    if keep_events_for == 0
      events.update_all expires_at: nil
    else
      events.update_all "expires_at = " + rdbms_date_add("created_at", "SECOND", keep_events_for.to_i)
    end
  end

  def trigger_web_request(request)
    params = request.params.except(:action, :controller, :agent_id, :user_id, :format)
    if respond_to?(:receive_webhook)
      Rails.logger.warn "DEPRECATED: The .receive_webhook method is deprecated, please switch your Agent to use .receive_web_request."
      receive_webhook(params).tap do
        self.last_web_request_at = Time.now
        save!
      end
    else
      handled_request =
        if method(:receive_web_request).arity == 1
          receive_web_request(request)
        else
          receive_web_request(params, request.method_symbol.to_s, request.format.to_s)
        end
      handled_request.tap do
        self.last_web_request_at = Time.now
        save!
      end
    end
  end

  def unavailable?
    disabled? || dependencies_missing?
  end

  def dependencies_missing?
    self.class.dependencies_missing?
  end

  def default_schedule
    self.class.default_schedule
  end

  def cannot_be_scheduled?
    self.class.cannot_be_scheduled?
  end

  def can_be_scheduled?
    !cannot_be_scheduled?
  end

  def cannot_receive_events?
    self.class.cannot_receive_events?
  end

  def can_receive_events?
    !cannot_receive_events?
  end

  def cannot_create_events?
    self.class.cannot_create_events?
  end

  def can_create_events?
    !cannot_create_events?
  end

  def can_control_other_agents?
    self.class.can_control_other_agents?
  end

  def can_dry_run?
    self.class.can_dry_run?
  end

  def no_bulk_receive?
    self.class.no_bulk_receive?
  end

  def log(message, options = {})
    AgentLog.log_for_agent(self, message, options.merge(inbound_event: current_event))
  end

  def error(message, options = {})
    log(message, options.merge(level: 4))
  end

  def delete_logs!
    logs.delete_all
    update_column :last_error_log_at, nil
  end

  def drop_pending_events
    false
  end

  def drop_pending_events=(bool)
    set_last_checked_event_id if bool
  end

  # Callbacks

  def set_default_schedule
    self.schedule = default_schedule unless schedule.present? || cannot_be_scheduled?
  end

  def unschedule_if_cannot_schedule
    self.schedule = nil if cannot_be_scheduled?
  end

  def set_last_checked_event_id
    if can_receive_events? && newest_event_id = Event.maximum(:id)
      self.last_checked_event_id = newest_event_id
    end
  end

  def possibly_update_event_expirations
    update_event_expirations! if saved_change_to_keep_events_for?
  end

  # Validation Methods

  private

  attr_accessor :current_event

  def validate_schedule
    unless cannot_be_scheduled?
      errors.add(:schedule, "is not a valid schedule") unless SCHEDULES.include?(schedule.to_s)
    end
  end

  def validate_options
    # Implement me in your subclass to test for valid options.
  end

  # Utility Methods

  def boolify(option_value)
    case option_value
    when true, 'true'
      true
    when false, 'false'
      false
    else
      nil
    end
  end

  def is_positive_integer?(value)
    Integer(value) >= 0
  rescue StandardError
    false
  end

  # Class Methods

  class << self
    def build_clone(original)
      new(original.slice(
        :type, :options, :service_id, :schedule, :controller_ids, :control_target_ids,
        :source_ids, :receiver_ids, :keep_events_for, :propagate_immediately, :scenario_ids
      )) { |clone|
        # Give it a unique name
        2.step do |i|
          name = '%s (%d)' % [original.name, i]
          unless exists?(name:)
            clone.name = name
            break
          end
        end
      }
    end

    def cannot_be_scheduled!
      @cannot_be_scheduled = true
    end

    def cannot_be_scheduled?
      !!@cannot_be_scheduled
    end

    def default_schedule(schedule = nil)
      @default_schedule = schedule unless schedule.nil?
      @default_schedule
    end

    def cannot_create_events!
      @cannot_create_events = true
    end

    def cannot_create_events?
      !!@cannot_create_events
    end

    def cannot_receive_events!
      @cannot_receive_events = true
    end

    def cannot_receive_events?
      !!@cannot_receive_events
    end

orgs/enterprise/blackbox-huginn/app/models/user.rb
# Huginn is designed to be a multi-User system.  Users have many Agents (and Events created by those Agents).
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :lockable, :omniauthable,
         *(:confirmable if ENV['REQUIRE_CONFIRMED_EMAIL'] == 'true')

  INVITATION_CODES = [ENV['INVITATION_CODE'] || 'try-huginn']

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: {
              with: /\A[a-zA-Z0-9_-]{3,190}\Z/,
              message: "can only contain letters, numbers, underscores, and dashes, and must be between 3 and 190 characters in length."
            }
  validates :invitation_code,
            inclusion: {
              in: INVITATION_CODES,
              message: "is not valid",
            },
            if: -> {
              !requires_no_invitation_code? && User.using_invitation_code?
            },
            on: :create

  has_many :user_credentials, dependent: :destroy, inverse_of: :user
  has_many :events, -> { order("events.created_at desc") }, dependent: :delete_all, inverse_of: :user
  has_many :agents, -> { order("agents.created_at desc") }, dependent: :destroy, inverse_of: :user
  has_many :logs, through: :agents, class_name: "AgentLog"
  has_many :scenarios, inverse_of: :user, dependent: :destroy
  has_many :services, -> { by_name('asc') }, dependent: :destroy

  def available_services
    Service.available_to_user(self).by_name
  end

  # Allow users to login via either email or username.
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def active?
    !deactivated_at
  end

  def deactivate!
    User.transaction do
      agents.update_all(deactivated: true)
      update_attribute(:deactivated_at, Time.now)
    end
  end

  def activate!
    User.transaction do
      agents.update_all(deactivated: false)
      update_attribute(:deactivated_at, nil)
    end
  end

  def active_for_authentication?
    super && active?
  end

  def inactive_message
    active? ? super : :deactivated_account
  end

  def self.using_invitation_code?
    ENV['SKIP_INVITATION_CODE'] != 'true'
  end

  def requires_no_invitation_code!
    @requires_no_invitation_code = true
  end

  def requires_no_invitation_code?
    !!@requires_no_invitation_code
  end

  def undefined_agent_types
    agents.reorder('').group(:type).pluck(:type).select do |type|
      type.constantize
      false
    rescue NameError
      true
    end
  end

  def undefined_agents
    agents.where(type: undefined_agent_types).select('id, schedule, events_count, type as undefined')
  end
end

orgs/enterprise/blackbox-huginn/app/views/agents/_action_menu.html.erb
<ul class="dropdown-menu" role="menu">
  <% if agent.can_be_scheduled? %>
    <li>
      <%= link_to icon_tag('glyphicon-refresh', class: 'color-success') + ' Run', run_agent_path(agent, return: return_to), method: :post, tabindex: "-1" %>
    </li>
  <% end %>

  <% if agent.can_dry_run? %>
    <li>
      <%= link_to icon_tag('glyphicon-refresh') + ' Dry Run', '#', 'data-action-url' => agent_dry_runs_path(agent), 'data-with-event-mode' => agent_dry_run_with_event_mode(agent), tabindex: "-1", onclick: "Utils.handleDryRunButton(this)" %>
    </li>
  <% end %>

  <li>
    <%= link_to icon_tag('glyphicon-eye-open') + ' Show'.html_safe, agent_path(agent, return: return_to) %>
  </li>

  <li class="divider"></li>

  <li>
    <%= link_to icon_tag('glyphicon-pencil') + ' Edit agent'.html_safe, edit_agent_path(agent, return: return_to) %>
  </li>

  <li>
    <%= link_to icon_tag('fa-copy') + ' Clone agent'.html_safe, new_agent_path(id: agent), tabindex: "-1" %>
  </li>

  <li>
    <%= link_to '#', 'data-toggle' => 'modal', 'data-target' => "#confirm-agent-enable-disable#{agent.id}" do %>
      <% if agent.disabled? %>
        <%= icon_tag('glyphicon-play') %> Enable agent
      <% else %>
        <%= icon_tag('glyphicon-pause') %> Disable agent
      <% end %>
    <% end %>
  </li>

  <% if agent.scenarios.length > 0 %>
    <li class="divider"></li>

    <% agent.scenarios.each do |scenario| %>
      <li>
        <%= link_to icon_tag('glyphicon-remove-circle', class: 'color-warning') + " Remove from #{scenario_label(scenario)}".html_safe, leave_scenario_agent_path(agent, scenario_id: scenario.to_param, return: return_to), method: :put, tabindex: "-1" %>
      </li>
    <% end %>
  <% end %>

  <% if agent.can_create_events? && agent.events_count > 0 %>
    <li class="divider"></li>

    <li>
      <%= link_to '#', 'data-toggle' => 'modal', 'data-target' => "#confirm-agent-reemit-events#{agent.id}" do %>
        <%= icon_tag('glyphicon-refresh') %> Re-emit all events
      <% end %>
    </li>
  <% end %>

  <li class="divider"></li>

  <% if agent.can_create_events? && agent.events_count > 0 %>
    <li>
      <%= link_to icon_tag('glyphicon-trash', class: 'color-danger') + ' Delete all events', remove_events_agent_path(agent, return: return_to), method: :delete, data: {confirm: 'Are you sure you want to delete ALL emitted events for this Agent?'}, tabindex: "-1" %>
    </li>
  <% end %>

  <li>
    <%= link_to icon_tag('glyphicon-remove', class: 'color-danger') + ' Delete agent', agent_path(agent, return: return_to), method: :delete, data: { confirm: 'Are you sure that you want to permanently delete this Agent?' }, tabindex: "-1" %>
  </li>
</ul>

<div id="confirm-agent-enable-disable<%= agent.id %>" class="confirm-agent modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmAgentLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Confirm</h4>
      </div>
      <div class="modal-body">
        <p><% if agent.disabled? %>Enable<% else %>Disable<% end %> &quot;<%= agent.name %>&quot;?</p>
      </div>
      <div class="modal-footer">
        <%= form_for(agent, as: :agent, url: agent_path(agent, return: return_to), method: 'PUT') do |f| %>
          <% if agent.disabled && agent.can_receive_events? %>
            <div class="form-group">
              <%= f.check_box :drop_pending_events %>
              <%= f.label :drop_pending_events, 'Drop pending events' %>
              <span class="glyphicon glyphicon-question-sign hover-help" data-content="As soon as you enable this agent, it starts to receive pending events that have not been processed while it was disabled.  To prevent that from happening, you can check this option."></span>
            </div>
          <% end %>
          <%= f.hidden_field :disabled, value: (!agent.disabled).to_s %>
          <%= f.button 'No', class: 'btn btn-default', 'data-dismiss' => 'modal' %>
          <%= f.submit 'Yes', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="confirm-agent-reemit-events<%= agent.id %>" class="confirm-agent modal fade" tabindex="-1" role="dialog" aria-labelledby="confirmAgentLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Confirm</h4>
      </div>
      <div class="modal-body">
        <p>Re-emit all events for &quot;<%= agent.name %>&quot;?</p>
      </div>
      <div class="modal-footer">
        <%= form_for(agent, as: :agent, url: reemit_events_agent_path(agent, return: return_to), method: 'POST') do |f| %>
          <% if agent.can_create_events? && agent.events_count > 0 %>
            <div class="form-group">
              <%= check_box_tag :delete_old_events %>
              <%= label_tag :delete_old_events, 'Delete old events' %>
              <span class="glyphicon glyphicon-question-sign hover-help" data-content="If this is checked, the original copies of the events will be deleted once they are re-emitted."></span>
            </div>
          <% end %>
          <%= f.button 'Cancel', class: 'btn btn-default', 'data-dismiss' => 'modal' %>
          <%= f.submit 'Re-emit all events', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

orgs/enterprise/blackbox-huginn/app/views/agents/_options.erb
<% if agent.is_form_configurable? %>
  <fieldset>
    <% if agent.persisted? %>
      <%= hidden_field_tag 'agent[type]', @agent.type %>
    <% end %>
    <legend>Options</legend>
    <% agent.form_configurable_attributes.each do |attribute| %>
      <div class="form-group">
        <%= label_tag attribute %>
        <%= agent.option_field_for(attribute) %>
        <span class="glyphicon glyphicon-ok form-control-feedback hidden"></span>
        <span class="glyphicon glyphicon-remove form-control-feedback hidden"></span>
      </div>
    <% end %>
  </fieldset>
<% else %>
  <div class="form-group">
    <%= label_tag :options %>
    <span class="glyphicon glyphicon-question-sign hover-help" data-content="In this JSON hash, interpolation is available in almost all values using the Liquid templating language.<p>Available template variables include the following:<dl><dt><code>message</code>, <code>url</code>, etc.</dt><dd>Refers to the corresponding key's value of each incoming event's payload.</dd><dt><code>agent</code></dt><dd>Refers to the agent that created each incoming event.  It has attributes like <code>type</code>, <code>name</code> and <code>options</code>, so <code>{{agent.type}}</code> will expand to <code>WebsiteAgent</code> if an incoming event is created by that agent.</dd></dl></p><p>To access user credentials, use the <code>credential</code> tag like this: <code>{% credential <em>bare_key_name</em> %}</code></p>"></span>
    <textarea rows="15" id="agent_options" name="agent[options]" class="form-control live-json-editor">
      <%= Utils.jsonify((agent.new_record? && agent.options == {}) ? agent.default_options : agent.options) %>
    </textarea>
  </div>
<% end %>
<div class="form-group">
  <%= submit_tag "Save", :class => "btn btn-primary" %>
  <% if agent.can_dry_run? %>
    <%= button_tag class: 'btn btn-default agent-dry-run-button', type: 'button', 'data-action-url' => agent.persisted? ? agent_dry_runs_path(agent) : dry_runs_path(type: agent.type), 'data-with-event-mode' => agent_dry_run_with_event_mode(agent) do %><%= icon_tag('glyphicon-refresh') %> Dry Run<% end %>
  <% end %>
</div>

orgs/enterprise/blackbox-huginn/app/views/agents/_table.html.erb
<div class='table-responsive'>
  <table class='table table-striped'>
    <tr>
      <th></th>
      <th><%= sortable_column 'name', 'asc' %></th>
      <th><%= sortable_column 'created_at', 'desc', name: 'Age' %></th>
      <th>Schedule</th>
      <th><%= sortable_column 'last_check_at', name: 'Last Check' %></th>
      <th><%= sortable_column 'last_event_at', name: 'Last Event Out' %></th>
      <th><%= sortable_column 'last_receive_at', name: 'Last Event In' %></th>
      <th>Events Created</th>
      <th>Working?</th>
      <th></th>
    </tr>

    <% @agents.each do |agent| %>
      <tr>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <%= agent_type_icon(agent, @agents) %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <%= link_to agent.name, agent_path(agent, return: (defined?(return_to) && return_to) || request.path) %>
          <br/>
          <span class='text-muted'><%= agent.short_type.titleize %></span>
          <% if agent.scenarios.present? %>
            <span>
              <%= scenario_links(agent) %>
            </span>
          <% end %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <%= time_ago_in_words agent.created_at %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <% if agent.can_be_scheduled? %>
            <%= agent_schedule(agent, ',<br/>') %>
          <% else %>
            <span class='not-applicable'></span>
          <% end %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <% if agent.can_be_scheduled? %>
            <%= agent.last_check_at ? time_ago_in_words(agent.last_check_at) + " ago" : "never" %>
          <% else %>
            <span class='not-applicable'></span>
          <% end %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <% if agent.can_create_events? %>
            <%= agent.last_event_at ? time_ago_in_words(agent.last_event_at) + " ago" : "never" %>
          <% else %>
            <span class='not-applicable'></span>
          <% end %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <% if agent.can_receive_events? %>
            <%= agent.last_receive_at ? time_ago_in_words(agent.last_receive_at) + " ago" : "never" %>
          <% else %>
            <span class='not-applicable'></span>
          <% end %>
        </td>
        <td class='<%= "agent-unavailable" if agent.unavailable? %>'>
          <% if agent.can_create_events? %>
            <%= link_to(agent.events_count || 0, agent_events_path(agent, return: (defined?(return_to) && return_to) || request.path)) %>
          <% else %>
            <span class='not-applicable'></span>
          <% end %>
        </td>
        <td><%= working(agent) %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-th-list"></span> Actions <span class="caret"></span>
            </button>
            <%= render 'agents/action_menu', agent: agent, return_to: (defined?(return_to) && return_to) || request.path %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= paginate @agents, :theme => 'twitter-bootstrap-3' %>

orgs/enterprise/blackbox-huginn/app/views/agents/edit.html.erb
<% content_for :title, "Edit " + @agent.name -%>

<div class='container'>
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h2>
          Editing your <%= @agent.short_type %>
          <%= image_tag "spinner-arrows.gif", :class => "spinner", :id => 'agent-spinner' %>
        </h2>
      </div>
    </div>
  </div>
  <div id="agent-form">
    <%= render 'form' %>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', agents_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-asterisk') + ' Show', agent_path(@agent), class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

orgs/enterprise/blackbox-huginn/app/views/agents/index.html.erb
<% content_for :title, "Agents" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <h2><%= session[:original_admin_user_id].present? ? "#{current_user.username}’s Agents" : 'Your Agents' %></h2>
      </div>

      <%= render 'agents/table' %>

      <br/>

      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-plus') + ' New Agent', new_agent_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-refresh') + ' Run event propagation', propagate_agents_path, method: 'post', class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-random') + ' View diagram', diagram_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-adjust') + toggle_disabled_text, toggle_visibility_agents_path, method: :put, class: "btn btn-default visibility-enabler" %>
      </div>
    </div>
  </div>
</div>